---

title: "Meow the cat and me ðŸ˜¸  ðŸ± "

date: 2020-07-13

---
theme: minima
title: Meow meow 
author: Rasa Salakij
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Feel free to browse documents related to cats I met. I believe cats are highly intelliget but also very ignorant. Share your experience with me. I would love to hear your story too!

# social links
twitter_username: yaorasa # DO NOT include the @ character, or else the build will fail!
github_username:  yaorasa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
